### PR TITLE
Update to Spring Boot 2.3

### LINKED ISSUE #1: Update guide to use R2DBC support in Spring Boot 2.3
As [suggested by @langley-agm](https://github.com/spring-projects/spring-boot/issues/20524#issuecomment-657136105), it would be good to update this guide to use the R2DBC support in Spring Boot 2.3 rather than the experimental project.

### PR DESCRIPTION
**Pull request by Brutus5000**
Closes #1 

This pull request is **not working** as there seems to be a backwards incompatible change with the handling of `schema.sql` files. I made this as I thought I was doing something wrong when following the guide. But digging deeper now, from my understanding `schema.sql` is only supported by Spring JDBC, but there is no point in adding jdbc dependencies for the sake of generating a schema. However flyway suffers from the same issue, so I'm not sure how to proceed here (I'm open for suggestions).

We could create the schema manually. But that is not what people want. Also the hint that schema.sql and flyway are not supported this way belong in this guide as well.

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@Brutus5000 Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-accessing-data-r2dbc&pullRequestId=2)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-accessing-data-r2dbc&pullRequestId=2) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@Brutus5000 Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-accessing-data-r2dbc&pullRequestId=2)!

**Comment by Brutus5000** [comment]
Ok I digged a bit deeper and it was fixed [here](https://github.com/spring-projects/spring-data-r2dbc/commit/82aad7c4f5395987662ee8b8682c94955d7fb2ad) but it might take a while until this is released in Spring Boot.

**Comment by mp911de** [comment]
Thanks for having a look. The full upgrade requires a few additional steps:

1. Initial: Migrate from experimental starter to Spring Boot proper (pom.xml and Gradle)
2. Initial: Migrate from experimental starter to Spring Boot proper (pom.xml)
3. Remove `dependencyManagement` for experimental starter
4. Config in `application.yml` can be removed entirely
5. Replace `spring-boot-test-autoconfigure-r2dbc` with `spring-boot-test`
6. Add `ConnectionFactoryInitializer` for `schema.sql`

Please let us know whether you want to look into these steps or whether we should close this PR and take a look ourselves.

**Comment by Brutus5000** [comment]
I checked this out once more. The `ResourceDatabasePopulator` required in the `ConnectionFactoryInitializer` requires Spring 5.3 / Spring Boot 2.4, which is only available as a milestone right now and I don't know how to set this up in Gradle. So I'd wait for Spring Boot 2.4 official release unless you have a better idea.

**Comment by mp911de** [comment]
`ConnectionFactoryInitializer` is available from Spring Data R2DBC (1.0) directly. With the migration to Boot 2.4, we will need to touch this guide again to update for deprecations.

**Comment by mp911de** [comment]
Closing in favor of e050c91.

**Comment by Brutus5000** [comment]
Yes, thanks I didn't find the time. Sorry.

**Pull request closed without merging**
